project:
  type: website
  output-dir: docs

execute: 
  freeze: false
  rpath: "/urs/local/bin/R"

website:
  title: "504"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/logistic-regression/index.qmd
        text: Logistic Regression
      - href: pages/ordinal-regression/index.qmd
        text: Ordinal Regression
      - href: pages/multinomial-regression/index.qmd
        text: Multinomial Regression
      - href: pages/poisson-regression/index.qmd
        text: Poisson Regression
      - href: about.qmd
        text: About
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



