project:
  type: website
  output-dir: docs

execute: 
  rpath: "/urs/local/bin/R"

website:
  title: "504"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



